/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package etollform;
import controller.ControlData;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author Freddy
 */
public class ViewEtool extends javax.swing.JFrame {

    /**
     * Creates new form ViewEtool
     */
    public ViewEtool() {
        initComponents();
        groupButton();
        groupButton2();
        groupButton1();
        groupButton3();
        groupButton4();
        groupButton5();
        menus.setVisible(false);
        login.setVisible(true);
        TopUp.setVisible(false);
        utama.setVisible(false);
        popup.setVisible(false);
        changedatatol.setVisible(false);
    }
    private int harga;
    private int golongan=0;
    private int saldotopup;
    private String pwddata;
    private String usrdata;
    private String inputdata;
    private int bayar;
    private File inputfile;
    private String asal="Waru";
    private String tujuan="Porong";
    private boolean[] kategori= {false,false,false,false,false,false};
    //private boolean[] tujuan= {false,false,false,false};
    private String proses()throws IOException
    {
        String temp=null;
        temp=ControlData.prosesdata(kategori,asal, tujuan, inputdata);
        return temp; 
    }
    private String bayar_tunai()throws IOException
    {
        String temp=null;
        temp=ControlData.bayar_tunai(bayar, kategori, asal, tujuan);
        return temp;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jLabel6 = new javax.swing.JLabel();
        popup = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        byr_tunai = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        utama = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Text1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        mobilkecil = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        truk2gardan = new javax.swing.JRadioButton();
        truk4gardan = new javax.swing.JRadioButton();
        truk5gardan = new javax.swing.JRadioButton();
        truk3gardan = new javax.swing.JRadioButton();
        prosesdata = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        s1 = new javax.swing.JRadioButton();
        w1 = new javax.swing.JRadioButton();
        p1 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        s2 = new javax.swing.JRadioButton();
        w2 = new javax.swing.JRadioButton();
        p2 = new javax.swing.JRadioButton();
        login = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        userid = new javax.swing.JTextField();
        userpass = new javax.swing.JPasswordField();
        menus = new javax.swing.JPanel();
        Tol = new javax.swing.JButton();
        topup = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        UbahDataTol = new javax.swing.JButton();
        TopUp = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        text2 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        prosesdatatopup = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        openfile = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        changedatatol = new javax.swing.JPanel();
        utama1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Text2 = new javax.swing.JTextField();
        mobilkecil2 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        truk2gardan2 = new javax.swing.JRadioButton();
        truk4gardan2 = new javax.swing.JRadioButton();
        truk5gardan2 = new javax.swing.JRadioButton();
        truk3gardan2 = new javax.swing.JRadioButton();
        prosesdata1 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jButton9 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        s3 = new javax.swing.JRadioButton();
        w3 = new javax.swing.JRadioButton();
        p3 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        s4 = new javax.swing.JRadioButton();
        w4 = new javax.swing.JRadioButton();
        p4 = new javax.swing.JRadioButton();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Jumlah Bayar :");

        byr_tunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byr_tunaiActionPerformed(evt);
            }
        });

        jButton2.setText("Proses");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Kembali ke Menu Utama");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout popupLayout = new javax.swing.GroupLayout(popup);
        popup.setLayout(popupLayout);
        popupLayout.setHorizontalGroup(
            popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, popupLayout.createSequentialGroup()
                .addGroup(popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(popupLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton3))
                    .addGroup(popupLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addGroup(popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(byr_tunai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );
        popupLayout.setVerticalGroup(
            popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popupLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(byr_tunai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(53, 53, 53))
        );

        jLabel1.setText("Input File Path : ");

        Text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text1ActionPerformed(evt);
            }
        });

        jButton1.setText("Open");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mobilkecil.setText("Sedan,Jip,Pickup,Truk Kecil,Bus");
        mobilkecil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilkecilActionPerformed(evt);
            }
        });

        jLabel2.setText("Kategori Mobil :");

        truk2gardan.setText("Truk dengan 2 gardan");
        truk2gardan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truk2gardanActionPerformed(evt);
            }
        });

        truk4gardan.setText("Truk dengan 4 gardan");
        truk4gardan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truk4gardanActionPerformed(evt);
            }
        });

        truk5gardan.setText("Truk dengan 5 gardan");
        truk5gardan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truk5gardanActionPerformed(evt);
            }
        });

        truk3gardan.setText("Truk dengan 3 gardan");
        truk3gardan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truk3gardanActionPerformed(evt);
            }
        });

        prosesdata.setText("Proses");
        prosesdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesdataActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Exit");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jButton7.setText("Menu Utama");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel9.setText("Asal :");

        s1.setText("Sidoarjo");
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });

        w1.setText("Waru");
        w1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w1ActionPerformed(evt);
            }
        });

        p1.setText("Porong");
        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Tujuan :");

        s2.setText("Sidoarjo");
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });

        w2.setText("Waru");
        w2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w2ActionPerformed(evt);
            }
        });

        p2.setText("Porong");
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout utamaLayout = new javax.swing.GroupLayout(utama);
        utama.setLayout(utamaLayout);
        utamaLayout.setHorizontalGroup(
            utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utamaLayout.createSequentialGroup()
                .addGroup(utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(utamaLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(s1)
                            .addComponent(prosesdata)
                            .addComponent(s2))
                        .addGap(39, 39, 39)
                        .addGroup(utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(utamaLayout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton2))
                            .addGroup(utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(utamaLayout.createSequentialGroup()
                                    .addComponent(w2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(p2))
                                .addGroup(utamaLayout.createSequentialGroup()
                                    .addComponent(w1)
                                    .addGap(27, 27, 27)
                                    .addComponent(p1)))))
                    .addGroup(utamaLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel9))
                    .addGroup(utamaLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel10)))
                .addGap(0, 120, Short.MAX_VALUE))
            .addGroup(utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(utamaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(utamaLayout.createSequentialGroup()
                            .addComponent(truk3gardan)
                            .addGap(0, 246, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, utamaLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Text1)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, utamaLayout.createSequentialGroup()
                            .addGroup(utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mobilkecil)
                                .addGroup(utamaLayout.createSequentialGroup()
                                    .addGap(137, 137, 137)
                                    .addComponent(jLabel2))
                                .addComponent(truk2gardan))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(truk5gardan, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(truk4gardan, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addContainerGap()))
        );
        utamaLayout.setVerticalGroup(
            utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, utamaLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1)
                    .addComponent(w1)
                    .addComponent(p1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(w2)
                    .addComponent(p2)
                    .addComponent(s2))
                .addGap(8, 8, 8)
                .addGroup(utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(prosesdata)
                    .addComponent(jToggleButton2))
                .addContainerGap())
            .addGroup(utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(utamaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(Text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel2)
                    .addGap(5, 5, 5)
                    .addGroup(utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mobilkecil)
                        .addComponent(truk4gardan))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(truk2gardan)
                        .addComponent(truk5gardan))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(truk3gardan)
                    .addContainerGap(123, Short.MAX_VALUE)))
        );

        jLabel4.setText("Username :");

        jLabel5.setText("Password :");

        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useridActionPerformed(evt);
            }
        });

        userpass.setText("jPasswordField1");
        userpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userpassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(97, 97, 97)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Login)
                    .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(userpass)
                        .addComponent(userid)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(userid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(userpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(Login)
                .addGap(54, 54, 54))
        );

        Tol.setText("Tol");
        Tol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TolActionPerformed(evt);
            }
        });

        topup.setText("Top Up");
        topup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topupActionPerformed(evt);
            }
        });

        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        UbahDataTol.setText("Ubah Data Tol");
        UbahDataTol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahDataTolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menusLayout = new javax.swing.GroupLayout(menus);
        menus.setLayout(menusLayout);
        menusLayout.setHorizontalGroup(
            menusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(menusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UbahDataTol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(topup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        menusLayout.setVerticalGroup(
            menusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Tol)
                .addGap(31, 31, 31)
                .addComponent(topup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(UbahDataTol)
                .addGap(38, 38, 38)
                .addComponent(jButton6)
                .addGap(32, 32, 32))
        );

        jLabel7.setText("Barcode Data :");

        jLabel8.setText("Jumlah Saldo :");

        text2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text2ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        prosesdatatopup.setText("Top Up");
        prosesdatatopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesdatatopupActionPerformed(evt);
            }
        });

        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        openfile.setText("Open");
        openfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openfileActionPerformed(evt);
            }
        });

        jButton4.setText("Menu Utama");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TopUpLayout = new javax.swing.GroupLayout(TopUp);
        TopUp.setLayout(TopUpLayout);
        TopUpLayout.setHorizontalGroup(
            TopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopUpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TopUpLayout.createSequentialGroup()
                        .addComponent(prosesdatatopup)
                        .addGap(31, 31, 31)
                        .addComponent(jButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TopUpLayout.createSequentialGroup()
                        .addGroup(TopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(40, 40, 40)
                        .addGroup(TopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(TopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(openfile))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        TopUpLayout.setVerticalGroup(
            TopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopUpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openfile))
                .addGap(18, 18, 18)
                .addGroup(TopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(TopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prosesdatatopup)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addGap(29, 29, 29))
        );

        jLabel11.setText("Harga : ");

        Text2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text2ActionPerformed(evt);
            }
        });

        mobilkecil2.setText("Sedan,Jip,Pickup,Truk Kecil,Bus");
        mobilkecil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilkecil2ActionPerformed(evt);
            }
        });

        jLabel12.setText("Kategori Mobil :");

        truk2gardan2.setText("Truk dengan 2 gardan");
        truk2gardan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truk2gardan2ActionPerformed(evt);
            }
        });

        truk4gardan2.setText("Truk dengan 4 gardan");
        truk4gardan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truk4gardan2ActionPerformed(evt);
            }
        });

        truk5gardan2.setText("Truk dengan 5 gardan");
        truk5gardan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truk5gardan2ActionPerformed(evt);
            }
        });

        truk3gardan2.setText("Truk dengan 3 gardan");
        truk3gardan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truk3gardan2ActionPerformed(evt);
            }
        });

        prosesdata1.setText("Proses");
        prosesdata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesdata1ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("Exit");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jButton9.setText("Menu Utama");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel13.setText("Asal :");

        s3.setText("Sidoarjo");
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });

        w3.setText("Waru");
        w3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w3ActionPerformed(evt);
            }
        });

        p3.setText("Porong");
        p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3ActionPerformed(evt);
            }
        });

        jLabel14.setText("Tujuan :");

        s4.setText("Sidoarjo");
        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });

        w4.setText("Waru");
        w4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w4ActionPerformed(evt);
            }
        });

        p4.setText("Porong");
        p4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout utama1Layout = new javax.swing.GroupLayout(utama1);
        utama1.setLayout(utama1Layout);
        utama1Layout.setHorizontalGroup(
            utama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utama1Layout.createSequentialGroup()
                .addGroup(utama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(utama1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(utama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(s3)
                            .addComponent(prosesdata1)
                            .addComponent(s4))
                        .addGap(39, 39, 39)
                        .addGroup(utama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(utama1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(utama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(truk5gardan2)
                                    .addComponent(truk4gardan2)))
                            .addGroup(utama1Layout.createSequentialGroup()
                                .addGroup(utama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(utama1Layout.createSequentialGroup()
                                        .addComponent(jButton9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(utama1Layout.createSequentialGroup()
                                        .addGroup(utama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(w4)
                                            .addComponent(w3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(utama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(p4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jToggleButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(23, 23, 23))))
                    .addGroup(utama1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel13))
                    .addGroup(utama1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel14)))
                .addGap(0, 38, Short.MAX_VALUE))
            .addGroup(utama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(utama1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(utama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, utama1Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Text2)
                            .addGap(77, 77, 77))
                        .addGroup(utama1Layout.createSequentialGroup()
                            .addGroup(utama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(truk3gardan2)
                                .addComponent(mobilkecil2)
                                .addGroup(utama1Layout.createSequentialGroup()
                                    .addGap(137, 137, 137)
                                    .addComponent(jLabel12))
                                .addComponent(truk2gardan2))
                            .addGap(0, 180, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        utama1Layout.setVerticalGroup(
            utama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, utama1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(truk4gardan2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(truk5gardan2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(utama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s3)
                    .addComponent(w3)
                    .addComponent(p3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(utama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(w4)
                    .addComponent(p4)
                    .addComponent(s4))
                .addGap(8, 8, 8)
                .addGroup(utama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(prosesdata1)
                    .addComponent(jToggleButton3))
                .addContainerGap())
            .addGroup(utama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(utama1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(utama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(Text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel12)
                    .addGap(5, 5, 5)
                    .addComponent(mobilkecil2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(truk2gardan2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(truk3gardan2)
                    .addContainerGap(148, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout changedatatolLayout = new javax.swing.GroupLayout(changedatatol);
        changedatatol.setLayout(changedatatolLayout);
        changedatatolLayout.setHorizontalGroup(
            changedatatolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
            .addGroup(changedatatolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(changedatatolLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(utama1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        changedatatolLayout.setVerticalGroup(
            changedatatolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 291, Short.MAX_VALUE)
            .addGroup(changedatatolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(utama1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(popup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(utama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(menus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(TopUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(changedatatol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(popup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(utama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(menus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(TopUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(changedatatol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int retval = fileChooser.showOpenDialog(this);
        if (retval==JFileChooser.APPROVE_OPTION)
        {
            inputfile = fileChooser.getSelectedFile();
            inputdata = String.valueOf(inputfile);
            Text1.setText(inputdata);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text1ActionPerformed
           String temp=Text1.getText();
           if(inputdata!=temp)inputdata=temp;
               
    }//GEN-LAST:event_Text1ActionPerformed

    private void mobilkecilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilkecilActionPerformed
        if(mobilkecil.isSelected())
            kategori[0]=true;
        else
            kategori[0]=false;
    }//GEN-LAST:event_mobilkecilActionPerformed

    private void truk3gardanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truk3gardanActionPerformed
        if(truk3gardan.isSelected())
            kategori[2]=true;
        else
            kategori[2]=false;
    }//GEN-LAST:event_truk3gardanActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void truk2gardanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truk2gardanActionPerformed
        if(truk2gardan.isSelected())
            kategori[1]=true;
        else
            kategori[1]=false;
    }//GEN-LAST:event_truk2gardanActionPerformed

    private void truk4gardanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truk4gardanActionPerformed
       if(truk4gardan.isSelected())
            kategori[3]=true;
        else
            kategori[3]=false;
    }//GEN-LAST:event_truk4gardanActionPerformed

    private void truk5gardanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truk5gardanActionPerformed
       if(truk5gardan.isSelected())
            kategori[4]=true;
        else
            kategori[4]=false;
    }//GEN-LAST:event_truk5gardanActionPerformed
    
    private void prosesdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesdataActionPerformed
        String data="";
        try {
            data=proses();
        } catch (IOException ex) {
            Logger.getLogger(ViewEtool.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(data!=null)
        {
                if(data=="maaf,saldo anda tidak cukup\n")
                {
                    int result=JOptionPane.showConfirmDialog(rootPane, data+"\n Mau Bayar Tunai?\n", "Hasil", JOptionPane.INFORMATION_MESSAGE);
                    if(result==JOptionPane.OK_OPTION)
                    {
                        menus.setVisible(false);
                        login.setVisible(false);
                        TopUp.setVisible(false);
                        utama.setVisible(false);
                        popup.setVisible(true);
                        changedatatol.setVisible(false);
                    }
                }
                else
                {
                    int result=JOptionPane.showConfirmDialog(rootPane, data+"mau buka portal\n","Buka Portal",JOptionPane.INFORMATION_MESSAGE);
                    if(result==JOptionPane.OK_OPTION)
                    {
                        JOptionPane.showMessageDialog(rootPane, "gate terbuka\n");
                        
                    }
                }
                    
        }
        
    }//GEN-LAST:event_prosesdataActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String data=null;
        try {
            data=bayar_tunai();
        } catch (IOException ex) {
            Logger.getLogger(ViewEtool.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(data!=null)
        {
            if(data.equals("Error \n"))
            {
                JOptionPane.showMessageDialog(rootPane, data);
            }
            else
            {
                int result=JOptionPane.showConfirmDialog(rootPane, data+"mau buka portal\n","Buka Portal",JOptionPane.INFORMATION_MESSAGE);
                if(result==JOptionPane.OK_OPTION)
                {
                    JOptionPane.showMessageDialog(rootPane, "gate terbuka\n");
                    menus.setVisible(false);
                    login.setVisible(false);
                    TopUp.setVisible(false);
                    utama.setVisible(true);
                    popup.setVisible(false);
                    changedatatol.setVisible(false);
                }   
            }
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void byr_tunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byr_tunaiActionPerformed
        bayar=Integer.parseInt(byr_tunai.getText());
        
    }//GEN-LAST:event_byr_tunaiActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        menus.setVisible(false);
        login.setVisible(false);
        TopUp.setVisible(false);
        utama.setVisible(true);
        popup.setVisible(false);
        changedatatol.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void userpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userpassActionPerformed
        pwddata=String.valueOf(userpass.getPassword());
    }//GEN-LAST:event_userpassActionPerformed

    private void useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useridActionPerformed
          usrdata=userid.getText();
    }//GEN-LAST:event_useridActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        boolean Log=false;
        Log=ControlData.login(usrdata, pwddata);
        //System.out.println(usrdata+" "+pwddata);
        if(Log)
        {
            menus.setVisible(true);
            login.setVisible(false);
            TopUp.setVisible(false);
            utama.setVisible(false);
            popup.setVisible(false);
            changedatatol.setVisible(false);
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void TolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TolActionPerformed
        menus.setVisible(false);
        login.setVisible(false);
        TopUp.setVisible(false);
        utama.setVisible(true);
        popup.setVisible(false);
        changedatatol.setVisible(false);
    }//GEN-LAST:event_TolActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(1);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void topupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topupActionPerformed
        menus.setVisible(false);
        login.setVisible(false);
        TopUp.setVisible(true);
        utama.setVisible(false);
        popup.setVisible(false);
        changedatatol.setVisible(false);
    }//GEN-LAST:event_topupActionPerformed

    private void text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       System.exit(1);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        saldotopup=Integer.parseInt(jTextField2.getText());
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void openfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openfileActionPerformed
        int retval = fileChooser.showOpenDialog(this);
        if (retval==JFileChooser.APPROVE_OPTION)
        {
            inputfile = fileChooser.getSelectedFile();
            inputdata = String.valueOf(inputfile);
            text2.setText(inputdata);
        }
    }//GEN-LAST:event_openfileActionPerformed

    private void prosesdatatopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesdatatopupActionPerformed
        boolean hasildatatopup= ControlData.topup(inputdata, saldotopup);
        if(hasildatatopup)
        {
            JOptionPane.showMessageDialog(rootPane, "Top Up Berhasil");
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Top Up Gagal");
        }
    }//GEN-LAST:event_prosesdatatopupActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        menus.setVisible(true);
        login.setVisible(false);
        TopUp.setVisible(false);
        utama.setVisible(false);
        popup.setVisible(false);
        changedatatol.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        menus.setVisible(true);
        login.setVisible(false);
        TopUp.setVisible(false);
        utama.setVisible(false);
        popup.setVisible(false);
        changedatatol.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        if(s1.isSelected())
        {
            asal="Sidoarjo";
        }
        else
        {
            asal="Waru";
        }
    }//GEN-LAST:event_s1ActionPerformed

    private void w1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w1ActionPerformed
        if(w1.isSelected())
        {
            asal="Waru";
        }
    }//GEN-LAST:event_w1ActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        if(p1.isSelected())
        {
            asal="Porong";
        }
        else
            asal="Waru";
    }//GEN-LAST:event_p1ActionPerformed

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        if(s2.isSelected())
        {
            tujuan ="Sidoarjo";
        }
        else tujuan="Porong";
    }//GEN-LAST:event_s2ActionPerformed

    private void w2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w2ActionPerformed
        if(w2.isSelected())
        {
            tujuan="Waru";
        }
        else
             tujuan="Porong";
    }//GEN-LAST:event_w2ActionPerformed

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        if(p2.isSelected())
        {
            tujuan="Porong";
        }
        else
            tujuan="Porong";
    }//GEN-LAST:event_p2ActionPerformed

    private void Text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text2ActionPerformed
        harga= Integer.parseInt(Text2.getText());
    }//GEN-LAST:event_Text2ActionPerformed

    private void mobilkecil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilkecil2ActionPerformed
        if(mobilkecil2.isSelected())
        {
            golongan=1;
        }
        else golongan=0;
    }//GEN-LAST:event_mobilkecil2ActionPerformed

    private void truk2gardan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truk2gardan2ActionPerformed
        if(truk2gardan2.isSelected())
        {
            golongan=2;
        }
        else golongan=0;
    }//GEN-LAST:event_truk2gardan2ActionPerformed

    private void truk4gardan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truk4gardan2ActionPerformed
        if(truk4gardan2.isSelected())
        {
            golongan=4;
        }
        else golongan=0;
    }//GEN-LAST:event_truk4gardan2ActionPerformed

    private void truk5gardan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truk5gardan2ActionPerformed
        if(truk5gardan2.isSelected())
        {
            golongan=5;
        }
        else golongan=0;
    }//GEN-LAST:event_truk5gardan2ActionPerformed

    private void truk3gardan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truk3gardan2ActionPerformed
        if(truk3gardan2.isSelected())
        {
            golongan=3;
        }
        else golongan=0;
    }//GEN-LAST:event_truk3gardan2ActionPerformed

    private void prosesdata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesdata1ActionPerformed
        boolean hasilolahdata=false;
        hasilolahdata=ControlData.updatehargatol(golongan, harga, tujuan, asal);
        if(hasilolahdata==true)
        {
            JOptionPane.showMessageDialog(rootPane, "Update Sukses\n");
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Update Failed\n");
        }
    }//GEN-LAST:event_prosesdata1ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        System.exit(1);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        menus.setVisible(true);
        login.setVisible(false);
        TopUp.setVisible(false);
        utama.setVisible(false);
        popup.setVisible(false);
        changedatatol.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
       if(s3.isSelected())
        {
            asal="Sidoarjo";
        }
        else
        {
            asal="Waru";
        }
    }//GEN-LAST:event_s3ActionPerformed

    private void w3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w3ActionPerformed
        if(w3.isSelected())
        {
            asal="Waru";
        }
    }//GEN-LAST:event_w3ActionPerformed

    private void p3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3ActionPerformed
        if(p3.isSelected())
        {
            asal="Porong";
        }
        else
            asal="Waru";
    }//GEN-LAST:event_p3ActionPerformed

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed
        if(s4.isSelected())
        {
            tujuan ="Sidoarjo";
        }
        else tujuan="Porong";
    }//GEN-LAST:event_s4ActionPerformed

    private void w4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w4ActionPerformed
        if(w4.isSelected())
        {
            tujuan="Waru";
        }
        else
             tujuan="Porong";
    }//GEN-LAST:event_w4ActionPerformed

    private void p4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4ActionPerformed
        if(p4.isSelected())
        {
            tujuan="Porong";
        }
        else
            tujuan="Porong";
    }//GEN-LAST:event_p4ActionPerformed

    private void UbahDataTolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahDataTolActionPerformed
        menus.setVisible(false);
        login.setVisible(false);
        TopUp.setVisible(false);
        utama.setVisible(false);
        popup.setVisible(false);
        changedatatol.setVisible(true);
    }//GEN-LAST:event_UbahDataTolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEtool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEtool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEtool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEtool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEtool().setVisible(true);
            }
        });
    }
    private void groupButton()
    {
        ButtonGroup bg1=new ButtonGroup();
        bg1.add(truk2gardan);
        bg1.add(truk3gardan);
        bg1.add(truk4gardan);
        bg1.add(truk5gardan);
        bg1.add(mobilkecil);
    }
    private void groupButton1()
    {
        ButtonGroup bg2= new ButtonGroup();
        bg2.add(p1);
        bg2.add(w1);
        bg2.add(s1);
    }
    private void groupButton2()
    {
        ButtonGroup bg3= new ButtonGroup();
        bg3.add(p2);
        bg3.add(w2);
        bg3.add(s2);
    }
    private void groupButton3()
    {
        ButtonGroup bg4= new ButtonGroup();
        bg4.add(p3);
        bg4.add(w3);
        bg4.add(s3);
    }
    private void groupButton4()
    {
        ButtonGroup bg5= new ButtonGroup();
        bg5.add(p4);
        bg5.add(w4);
        bg5.add(s4);
    }
    private void groupButton5()
    {
        ButtonGroup bg6=new ButtonGroup();
        bg6.add(truk2gardan2);
        bg6.add(truk3gardan2);
        bg6.add(truk4gardan2);
        bg6.add(truk5gardan2);
        bg6.add(mobilkecil2);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JTextField Text1;
    private javax.swing.JTextField Text2;
    private javax.swing.JButton Tol;
    private javax.swing.JPanel TopUp;
    private javax.swing.JButton UbahDataTol;
    private javax.swing.JTextField byr_tunai;
    private javax.swing.JPanel changedatatol;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JPanel login;
    private javax.swing.JPanel menus;
    private javax.swing.JRadioButton mobilkecil;
    private javax.swing.JRadioButton mobilkecil2;
    private javax.swing.JButton openfile;
    private javax.swing.JRadioButton p1;
    private javax.swing.JRadioButton p2;
    private javax.swing.JRadioButton p3;
    private javax.swing.JRadioButton p4;
    private javax.swing.JPanel popup;
    private javax.swing.JToggleButton prosesdata;
    private javax.swing.JToggleButton prosesdata1;
    private javax.swing.JButton prosesdatatopup;
    private javax.swing.JRadioButton s1;
    private javax.swing.JRadioButton s2;
    private javax.swing.JRadioButton s3;
    private javax.swing.JRadioButton s4;
    private javax.swing.JTextField text2;
    private javax.swing.JButton topup;
    private javax.swing.JRadioButton truk2gardan;
    private javax.swing.JRadioButton truk2gardan2;
    private javax.swing.JRadioButton truk3gardan;
    private javax.swing.JRadioButton truk3gardan2;
    private javax.swing.JRadioButton truk4gardan;
    private javax.swing.JRadioButton truk4gardan2;
    private javax.swing.JRadioButton truk5gardan;
    private javax.swing.JRadioButton truk5gardan2;
    private javax.swing.JTextField userid;
    private javax.swing.JPasswordField userpass;
    private javax.swing.JPanel utama;
    private javax.swing.JPanel utama1;
    private javax.swing.JRadioButton w1;
    private javax.swing.JRadioButton w2;
    private javax.swing.JRadioButton w3;
    private javax.swing.JRadioButton w4;
    // End of variables declaration//GEN-END:variables
}
