/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package etollform;
import controller.ControlData;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author Freddy
 */
public class ViewEtool extends javax.swing.JFrame {

    /**
     * Creates new form ViewEtool
     */
    public ViewEtool() {
        initComponents();
        groupButton();
        menus.setVisible(false);
        login.setVisible(true);
        TopUp.setVisible(false);
        utama.setVisible(false);
        popup.setVisible(false);
    }
    private int saldotopup;
    private String pwddata;
    private String usrdata;
    private String inputdata;
    private int bayar;
    private File inputfile;
    private String asal="Waru";
    private String tujuan="Porong";
    private boolean[] kategori= {false,false,false,false,false,false};
    //private boolean[] tujuan= {false,false,false,false};
    private String proses()throws IOException
    {
        String temp=null;
        temp=ControlData.prosesdata(kategori,asal, tujuan, inputdata);
        return temp; 
    }
    private String bayar_tunai()throws IOException
    {
        String temp=null;
        temp=ControlData.bayar_tunai(bayar, kategori, asal, tujuan);
        return temp;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jLabel6 = new javax.swing.JLabel();
        popup = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        byr_tunai = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        utama = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Text1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        mobilkecil = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        truk2gardan = new javax.swing.JRadioButton();
        truk4gardan = new javax.swing.JRadioButton();
        truk5gardan = new javax.swing.JRadioButton();
        truk3gardan = new javax.swing.JRadioButton();
        prosesdata = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton7 = new javax.swing.JButton();
        login = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        userid = new javax.swing.JTextField();
        userpass = new javax.swing.JPasswordField();
        menus = new javax.swing.JPanel();
        Tol = new javax.swing.JButton();
        topup = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        TopUp = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        text2 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        prosesdatatopup = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        openfile = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Jumlah Bayar :");

        byr_tunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byr_tunaiActionPerformed(evt);
            }
        });

        jButton2.setText("Proses");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Kembali ke Menu Utama");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout popupLayout = new javax.swing.GroupLayout(popup);
        popup.setLayout(popupLayout);
        popupLayout.setHorizontalGroup(
            popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, popupLayout.createSequentialGroup()
                .addGroup(popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(popupLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton3))
                    .addGroup(popupLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addGroup(popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(byr_tunai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );
        popupLayout.setVerticalGroup(
            popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popupLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(byr_tunai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(popupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(53, 53, 53))
        );

        jLabel1.setText("Input File Path : ");

        Text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text1ActionPerformed(evt);
            }
        });

        jButton1.setText("Open");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mobilkecil.setText("Sedan,Jip,Pickup,Truk Kecil,Bus");
        mobilkecil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilkecilActionPerformed(evt);
            }
        });

        jLabel2.setText("Kategori Mobil :");

        truk2gardan.setText("Truk dengan 2 gardan");
        truk2gardan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truk2gardanActionPerformed(evt);
            }
        });

        truk4gardan.setText("Truk dengan 4 gardan");
        truk4gardan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truk4gardanActionPerformed(evt);
            }
        });

        truk5gardan.setText("Truk dengan 5 gardan");
        truk5gardan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truk5gardanActionPerformed(evt);
            }
        });

        truk3gardan.setText("Truk dengan 3 gardan");
        truk3gardan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truk3gardanActionPerformed(evt);
            }
        });

        prosesdata.setText("Proses");
        prosesdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesdataActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Exit");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jButton7.setText("Menu Utama");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout utamaLayout = new javax.swing.GroupLayout(utama);
        utama.setLayout(utamaLayout);
        utamaLayout.setHorizontalGroup(
            utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utamaLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(prosesdata)
                .addGap(43, 43, 43)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jToggleButton2)
                .addGap(46, 46, 46))
            .addGroup(utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(utamaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(utamaLayout.createSequentialGroup()
                            .addComponent(truk3gardan)
                            .addGap(0, 246, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, utamaLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Text1)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, utamaLayout.createSequentialGroup()
                            .addGroup(utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mobilkecil)
                                .addGroup(utamaLayout.createSequentialGroup()
                                    .addGap(137, 137, 137)
                                    .addComponent(jLabel2))
                                .addComponent(truk2gardan))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(truk5gardan, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(truk4gardan, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addContainerGap()))
        );
        utamaLayout.setVerticalGroup(
            utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, utamaLayout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addGroup(utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prosesdata)
                    .addComponent(jToggleButton2)
                    .addComponent(jButton7))
                .addGap(61, 61, 61))
            .addGroup(utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(utamaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(Text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel2)
                    .addGap(5, 5, 5)
                    .addGroup(utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mobilkecil)
                        .addComponent(truk4gardan))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(truk2gardan)
                        .addComponent(truk5gardan))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(truk3gardan)
                    .addContainerGap(123, Short.MAX_VALUE)))
        );

        jLabel4.setText("Username :");

        jLabel5.setText("Password :");

        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useridActionPerformed(evt);
            }
        });

        userpass.setText("jPasswordField1");
        userpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userpassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(97, 97, 97)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Login)
                    .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(userpass)
                        .addComponent(userid)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(userid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(userpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(Login)
                .addGap(54, 54, 54))
        );

        Tol.setText("Tol");
        Tol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TolActionPerformed(evt);
            }
        });

        topup.setText("Top Up");
        topup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topupActionPerformed(evt);
            }
        });

        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menusLayout = new javax.swing.GroupLayout(menus);
        menus.setLayout(menusLayout);
        menusLayout.setHorizontalGroup(
            menusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(menusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(topup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        menusLayout.setVerticalGroup(
            menusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Tol)
                .addGap(31, 31, 31)
                .addComponent(topup)
                .addGap(38, 38, 38)
                .addComponent(jButton6)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jLabel7.setText("Barcode Data :");

        jLabel8.setText("Jumlah Saldo :");

        text2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text2ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        prosesdatatopup.setText("Top Up");
        prosesdatatopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesdatatopupActionPerformed(evt);
            }
        });

        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        openfile.setText("Open");
        openfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openfileActionPerformed(evt);
            }
        });

        jButton4.setText("Menu Utama");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TopUpLayout = new javax.swing.GroupLayout(TopUp);
        TopUp.setLayout(TopUpLayout);
        TopUpLayout.setHorizontalGroup(
            TopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopUpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TopUpLayout.createSequentialGroup()
                        .addComponent(prosesdatatopup)
                        .addGap(31, 31, 31)
                        .addComponent(jButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TopUpLayout.createSequentialGroup()
                        .addGroup(TopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(40, 40, 40)
                        .addGroup(TopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(TopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(openfile))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        TopUpLayout.setVerticalGroup(
            TopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopUpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openfile))
                .addGap(18, 18, 18)
                .addGroup(TopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(TopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prosesdatatopup)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(popup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(utama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(menus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(TopUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(popup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(utama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(menus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(TopUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int retval = fileChooser.showOpenDialog(this);
        if (retval==JFileChooser.APPROVE_OPTION)
        {
            inputfile = fileChooser.getSelectedFile();
            inputdata = String.valueOf(inputfile);
            Text1.setText(inputdata);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text1ActionPerformed
           String temp=Text1.getText();
           if(inputdata!=temp)inputdata=temp;
               
    }//GEN-LAST:event_Text1ActionPerformed

    private void mobilkecilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilkecilActionPerformed
        if(mobilkecil.isSelected())
            kategori[0]=true;
        else
            kategori[0]=false;
    }//GEN-LAST:event_mobilkecilActionPerformed

    private void truk3gardanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truk3gardanActionPerformed
        if(truk3gardan.isSelected())
            kategori[2]=true;
        else
            kategori[2]=false;
    }//GEN-LAST:event_truk3gardanActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void truk2gardanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truk2gardanActionPerformed
        if(truk2gardan.isSelected())
            kategori[1]=true;
        else
            kategori[1]=false;
    }//GEN-LAST:event_truk2gardanActionPerformed

    private void truk4gardanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truk4gardanActionPerformed
       if(truk4gardan.isSelected())
            kategori[3]=true;
        else
            kategori[3]=false;
    }//GEN-LAST:event_truk4gardanActionPerformed

    private void truk5gardanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truk5gardanActionPerformed
       if(truk5gardan.isSelected())
            kategori[4]=true;
        else
            kategori[4]=false;
    }//GEN-LAST:event_truk5gardanActionPerformed
    
    private void prosesdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesdataActionPerformed
        String data="";
        try {
            data=proses();
        } catch (IOException ex) {
            Logger.getLogger(ViewEtool.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(data!=null)
        {
                if(data=="maaf,saldo anda tidak cukup\n")
                {
                    int result=JOptionPane.showConfirmDialog(rootPane, data+"\n Mau Bayar Tunai?\n", "Hasil", JOptionPane.INFORMATION_MESSAGE);
                    if(result==JOptionPane.OK_OPTION)
                    {
                        menus.setVisible(false);
                        login.setVisible(false);
                        TopUp.setVisible(false);
                        utama.setVisible(false);
                        popup.setVisible(true);
                    }
                }
                else
                {
                    int result=JOptionPane.showConfirmDialog(rootPane, data+"mau buka portal\n","Buka Portal",JOptionPane.INFORMATION_MESSAGE);
                    if(result==JOptionPane.OK_OPTION)
                    {
                        JOptionPane.showMessageDialog(rootPane, "gate terbuka\n");
                        
                    }
                }
                    
        }
        
    }//GEN-LAST:event_prosesdataActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String data=null;
        try {
            data=bayar_tunai();
        } catch (IOException ex) {
            Logger.getLogger(ViewEtool.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(data!=null)
        {
            if(data.equals("Error \n"))
            {
                JOptionPane.showMessageDialog(rootPane, data);
            }
            else
            {
                int result=JOptionPane.showConfirmDialog(rootPane, data+"mau buka portal\n","Buka Portal",JOptionPane.INFORMATION_MESSAGE);
                if(result==JOptionPane.OK_OPTION)
                {
                    JOptionPane.showMessageDialog(rootPane, "gate terbuka\n");
                    menus.setVisible(false);
                    login.setVisible(false);
                    TopUp.setVisible(false);
                    utama.setVisible(true);
                    popup.setVisible(false);
                }   
            }
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void byr_tunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byr_tunaiActionPerformed
        bayar=Integer.parseInt(byr_tunai.getText());
        
    }//GEN-LAST:event_byr_tunaiActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        menus.setVisible(false);
        login.setVisible(false);
        TopUp.setVisible(false);
        utama.setVisible(true);
        popup.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void userpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userpassActionPerformed
        pwddata=String.valueOf(userpass.getPassword());
    }//GEN-LAST:event_userpassActionPerformed

    private void useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useridActionPerformed
          usrdata=userid.getText();
    }//GEN-LAST:event_useridActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        boolean Log=false;
        Log=ControlData.login(usrdata, pwddata);
        //System.out.println(usrdata+" "+pwddata);
        if(Log)
        {
            menus.setVisible(true);
            login.setVisible(false);
            TopUp.setVisible(false);
            utama.setVisible(false);
            popup.setVisible(false);
            System.out.println("a");
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void TolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TolActionPerformed
        menus.setVisible(false);
        login.setVisible(false);
        TopUp.setVisible(false);
        utama.setVisible(true);
        popup.setVisible(false);
    }//GEN-LAST:event_TolActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(1);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void topupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topupActionPerformed
        menus.setVisible(false);
        login.setVisible(false);
        TopUp.setVisible(true);
        utama.setVisible(false);
        popup.setVisible(false);
    }//GEN-LAST:event_topupActionPerformed

    private void text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       System.exit(1);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        saldotopup=Integer.parseInt(jTextField2.getText());
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void openfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openfileActionPerformed
        int retval = fileChooser.showOpenDialog(this);
        if (retval==JFileChooser.APPROVE_OPTION)
        {
            inputfile = fileChooser.getSelectedFile();
            inputdata = String.valueOf(inputfile);
            text2.setText(inputdata);
        }
    }//GEN-LAST:event_openfileActionPerformed

    private void prosesdatatopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesdatatopupActionPerformed
        boolean hasildatatopup= ControlData.topup(inputdata, saldotopup);
        if(hasildatatopup)
        {
            JOptionPane.showMessageDialog(rootPane, "Top Up Berhasil");
        }
    }//GEN-LAST:event_prosesdatatopupActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        menus.setVisible(true);
        login.setVisible(false);
        TopUp.setVisible(false);
        utama.setVisible(false);
        popup.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        menus.setVisible(true);
        login.setVisible(false);
        TopUp.setVisible(false);
        utama.setVisible(false);
        popup.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEtool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEtool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEtool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEtool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEtool().setVisible(true);
            }
        });
    }
    private void groupButton()
    {
        ButtonGroup bg1=new ButtonGroup();
        bg1.add(truk2gardan);
        bg1.add(truk3gardan);
        bg1.add(truk4gardan);
        bg1.add(truk5gardan);
        bg1.add(mobilkecil);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JTextField Text1;
    private javax.swing.JButton Tol;
    private javax.swing.JPanel TopUp;
    private javax.swing.JTextField byr_tunai;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JPanel login;
    private javax.swing.JPanel menus;
    private javax.swing.JRadioButton mobilkecil;
    private javax.swing.JButton openfile;
    private javax.swing.JPanel popup;
    private javax.swing.JToggleButton prosesdata;
    private javax.swing.JButton prosesdatatopup;
    private javax.swing.JTextField text2;
    private javax.swing.JButton topup;
    private javax.swing.JRadioButton truk2gardan;
    private javax.swing.JRadioButton truk3gardan;
    private javax.swing.JRadioButton truk4gardan;
    private javax.swing.JRadioButton truk5gardan;
    private javax.swing.JTextField userid;
    private javax.swing.JPasswordField userpass;
    private javax.swing.JPanel utama;
    // End of variables declaration//GEN-END:variables
}
